# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    # increment_build_number(xcodeproj: "CDDA.xcodeproj")
    build_app(workspace: "CDDA.xcworkspace", scheme: "CBNfreeIAP")
    upload_to_testflight
    sentry
  end

  lane :clean do
    for scheme in ["CBN", "CBNfreeIAP"]
      xcclean workspace: "CDDA.xcworkspace", scheme: scheme
    end
  end

  lane :sentry do
    download_dsyms(version: 'latest', wait_for_dsym_processing: true)
    for dSYM_path in lane_context[SharedValues::DSYM_PATHS]
        puts dSYM_path
        sentry_upload_dsym(
          org_slug: 'ip-apollov-yuri-andreevich',
          project_slug: 'cataclysm-dda-ios',
          dsym_path: dSYM_path,
        )
    end
  end
end
